name: Test

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12

    - name: Install packages
      run: npm ci

    - name: Run linter
      run: npm run lint

  test:
    name: Test on Atom ${{ matrix.atom_channel }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: ['stable', 'beta']
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'

    - name: Get Revive
      env:
          GO111MODULE: 'on'
      run: go get -v -u github.com/mgechev/revive@v1

    - name: Check out
      uses: actions/checkout@v2

    - name: Set up Atom
      uses: UziTech/action-setup-atom@v1
      with:
        channel: ${{ matrix.channel }}

    - name: Get versions
      run: atom -v && apm -v

    - name: Install dependencies
      run: apm ci

    - name: Run tests
      run: apm test
