name: Test
on: push
jobs:

  test:
    name: Test on Atom ${{ matrix.atom_channel }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        atom_channel: ['stable', 'beta']
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Get Revive
      run: go get -v -u github.com/mgechev/revive

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      env:
        ATOM_CHANNEL: ${{ matrix.atom_channel }}
        ATOM_LINT_WITH_BUNDLED_NODE: 'true'
      run: |
        export OS=$(echo ${{ matrix.os }} | cut -f1 -d"-")
        if [ $OS = "ubuntu" ]; then export TRAVIS_OS_NAME=linux; \
        elif [ $OS = "macOS" ]; then export TRAVIS_OS_NAME=osx; \
        else echo "Unknown OS!"; exit 1; fi
        export PATH=$PATH:$(go env GOPATH)/bin
        curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
        chmod u+x build-package.sh
        ./build-package.sh
